### PR TITLE
read maximum number of server threads from CCLASH_MAX_SERVER_THREADS …

### PR DESCRIPTION
**Pull request by peschmae0**
…environment variable

### CODE REVIEW

**Comment by inorton** [comment]
Thanks :) looks good. What sort of situations were leading you to change it?

**Comment by peschmae0** [comment]
Compiling with 24 threads on an empty cache lead to permanent connection timeouts on the client.

Typically I only build with 12 threads on the 6 core (12 with hyperthreading) machine, but it is running a CI where several compilations may run at once. So I was testing those workloads.

CClashServerClient.cs was throwing a timeout in ncs.Connect(500) that was caught and logged on line 49. I am slightly doubtful as to the followup there (ncs.Dispose(); Open();) which leaves the client unconnected...

**Comment by inorton** [comment]
Thanks. That's good to know. Our deployment is a CI but we have many machines. Most of our builds don't manage more than 3 or 4 things at once and we tend to add more machines.

**Comment by peschmae0** [comment]
Got everything working just fine, I think. We'll see over the next few days.

One remaining issue however: how do you manage cache size? As it is, it keeps growing and growing...
I would need something akin to _ccache -M 20G_

**Pull request merged**
